procedure: format

projectLocation: 'C:\\github\\azure-sdk-for-java\\sdk\\resources\\mgmt\\src\\'

additionalProjects:
  - 'C:\\github\\azure-sdk-for-java\\sdk\\management\\azure\src\\test\\java\\'
  - 'C:\\github\\azure-sdk-for-java\\sdk\\management\\samples\src\\main\\java\\'
  - 'C:\\github\\azure-sdk-for-java\\sdk\\management\\samples\src\\test\\java\\'

referenceProjects:
  - 'C:\\github\\azure-sdk-for-java\\sdk\\resources\\mgmt\\src\\test\\java\\'
  - 'C:\\github\\azure-sdk-for-java\\sdk\\management\\azure\\src\\test\\java\\'
  - 'C:\\github\\azure-sdk-for-java\\sdk\\management\\samples\src\\test\\java\\'
